name: Testing github actions
on: 
  workflow_dispatch:
    branches:
    - develop
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
      tags:
        description: 'Testing'  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run task in ECS
      run: |
        TEST="127.0.0.1"
        echo "test $TEST 123"
